name = "rvy/rir3"
version = "0.1.2-rc.9"
description = "sync studio output to cli and also allow studio code execution from cli"
license = "MIT"
authors = ["rvy"]
private = false
includes = ["pesde.toml", "README.md", "LICENSE", "src/**/*.luau", "plugins/**/*.luau", "plugins/**/*.json", ".luaurc"]

[target]
environment = "lune"
bin = "src/init.luau"

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"

[dependencies.argparse]
name = "caveful_games/argparse"
version = "^0.1.2"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dependencies.chalk]
name = "kimpure/chalk_luau"
version = "^0.1.8"
index = "https://github.com/pesde-pkg/index"

[dependencies.pathfs]
name = "jiwonz/pathfs"
version = "^0.6.0"
index = "https://github.com/pesde-pkg/index"

[dev_dependencies.rojo]
name = "pesde/rojo"
version = "^7.5.1"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.selene]
name = "pesde/selene"
version = "^0.29.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.stylua]
name = "pesde/stylua"
version = "^2.3.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"
