name = "rvy/bench"
version = "0.1.0"
license = "MIT"
private = true

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dev_dependencies]
greentea = { name = "corecii/greentea", version = "^0.4.11" }
jest = { wally = "jsdotlua/jest", version = "^3.10.0" }
jest_globals = { wally = "jsdotlua/jest-globals", version = "^3.10.0" }