name = "corecii/greentea"
version = "0.4.11"
description = "A runtime typechecker with Luau types, pretty errors, and inspection"
license = "MIT"
authors = ["Corecii (Shae A.) <github.com/corecii>"]
repository = "https://github.com/Corecii/GreenTea"
private = false
includes = ["pesde.toml", "README.md", "CHANGELOG.md", "LICENSE", "src", "selene.toml", ".luaurc"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]
