name = "rvy/jestir"
version = "0.0.4-rc.3"
private = false
includes = ["pesde.toml", "README.md", "LICENSE", "src/**/*.luau", ".luaurc"]

[target]
environment = "lune"
bin = "src/init.luau"

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"

[dependencies.argparse]
name = "caveful_games/argparse"
version = "^0.1.2"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dependencies.rir3]
name = "rvy/rir3"
version = "^0.1.2-rc.4"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dependencies.rojo]
name = "pesde/rojo"
version = "^7.6.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.luau_lsp]
name = "pesde/luau_lsp"
version = "^1.55.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.pathfs]
name = "jiwonz/pathfs"
version = "^0.6.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.selene]
name = "pesde/selene"
version = "^0.29.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.stylua]
name = "pesde/stylua"
version = "^2.3.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"
